name: Misc
permissions:
  checks: write
  contents: write
on:
  push:
    branches: 
      - main
  pull_request:
    # The branches below must be a subset of the branches above
    branches: 
      - main

  # Allow manually running it.
  workflow_dispatch:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          
  check-spelling:
    # You may pin to the exact commit or the version.
    # uses: check-spelling/check-spelling@00c989c97749eb0cb2d256bdc55ac61b0096c6d3
    uses: check-spelling/check-spelling@main
    with:
      # The GITHUB_TOKEN secret
      GITHUB_TOKEN: ${{ github.token }}
      # Cache dictionaries
      cache-dictionaries: 1
